messages:
  #comming soon
  enabled: true

  nopermission: "You don't have permission to use this!"
  allexist: "Panel already exists!"
  successfullycreated: "Successfully created panel: %panelName%"
  successfullydeleted: "Successfully deleted panel: %panelName%"

api-key: "YOUR_API_KEY_HERE"
api-port: 5555